name: 'Zoocha CT Example starter'
description: 'This recipe installs an example Zoocha Example content type with some pre-defined fields.'
type: 'Content Type'

recipes:
  - zr-editorial-bundle
  - zr-layout-builder-bundle
  - zr-cb-accordion
  - zr-cb-cards
  - zr-cb-cta
  - zr-cb-copy-content
  - zr-cb-embedded-view
  - zr-cb-hero
  - zr-cb-links
  - zr-cb-media-content
  - zr-cb-webform
install:
  - paragraphs
  - workflows
  - content_moderation

config:
  strict: false
